### ISSUE TITLE
请问你们多久公布源代码

### ISSUE THREAD

**Issue by YankeeLiu** [chenhaokun/TPGR#2]
一直在关注你们这片文章，我也从事这方面的研究，看到你们延后了代码公布时间，我很想学习你们的模型和对比实验中DDPG-KNN的实现细节，非常感谢

**Comment by weicheng51** [comment]
@YankeeLiu 我最近也在研究这两篇论文 可以加个好友吗

**Comment by chenhaokun** [comment]
模型代码已发布，谢谢关注
